# Generated by Django 4.2.1 on 2023-06-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_db',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
